version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: otus_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data
