version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: otus_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: library:1.0 - если запускать из готового образа
    container_name: otus_library_app
    ports:
      - "8888:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/otus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
