spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otus
    username: postgres
    password: admin
  sql:
    init:
      mode: embedded
      data-locations: data.sql
      schema-locations: schema.sql